config/routes.rb
Personalwebsite::Application.routes.draw do

  devise_for :admins , :path => '',  :controllers => {:sessions => "sessions"} , :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :posts , only:[:show , :index]



  get "/" => "posts#index", :as => "root"
  get 'tags/:tag' => 'posts#index', as: "tag"

  get "about" , :controller => "static_pages" , :action => "about" , :as => "about"

  namespace :backend do
       devise_for :admins
        get "admin_index/index"
     root 'admin_index#index'
     resources :posts
     post "posts/preview" , to: "posts#preview"
     delete "posts/destroy" , to: 'posts#destroy'



  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :lockable , :rememberable, :trackable
end

app/models/post.rb
class Post < ActiveRecord::Base
   extend FriendlyId
  friendly_id :title,  use: :slugged
 validates_presence_of :title
 validates_presence_of :description
 #associations
 has_many :taggings
 has_many :tags, through: :taggings

 #tag methods

  def all_tags=(names)
   self.tags = names.split(",").map do |name|
     Tag.where(name: name.strip).first_or_create!
   end
  end


  def all_tags
   self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts()
    self.joins(:taggings).select('tags.*, count(tag_id) as "count"').group("tags.id").order('count desc')
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/backend/admin_index_controller.rb
class Backend::AdminIndexController < Backend::ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.all;
  end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ActionController::Base
   before_action :authenticate_admin!
   layout 'admin'
   protect_from_forgery
end

app/controllers/backend/posts_controller.rb
class Backend::PostsController < Backend::ResourceController


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "Post created!"
      redirect_to backend_root_path
     else
      redirect_to new_backend_post_path
    end
  end

  def index
    @posts = Post.all
  end



  def destroy
     @post = Post.find(params[:id])
     @post.destroy
    redirect_to root_path
  end

  def show

    @post = Post.friendly.find(params[:id])
  end

  def edit
    @post = Post.friendly.find(params[:id])

  end

  def preview
    @description = params[:description]
   render :partial => 'preview', :content_type => 'text/html'
  end

  def update
   @post = Post.friendly.find(params[:id])
   @post.update_attributes(post_params)

   if @post.save
    flash[:notice] = "Post updated!"
    redirect_to backend_root_path
   else
    redirect_to new_backend_post_path
   end
  end

  private

  def post_params
    params.require(:post).permit( :title, :description , :all_tags)

  end
end

app/controllers/backend/resource_controller.rb
class Backend::ResourceController < Backend::ApplicationController 
  
   inherit_resources
  respond_to :html
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_filter :set_archive

 layout 'show' , :only => [:show]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all.order("created_at DESC")
    end
  end



  def show
    @post = Post.friendly.find(params[:id])
  end


private
  def set_archive
    @posts = Post.all(:select => "id, title,  created_at", :order => "created_at DESC")
    @post_months = @posts.group_by { |t| t.created_at.beginning_of_year }
  end


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

   def new
     @posts = Post.all(:select => "id, title,  created_at", :order => "created_at DESC")
     @post_months = @posts.group_by { |t| t.created_at.beginning_of_year }
     super

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_filter :set_nav
      layout 'about' , :only => [:about]
  def about

  end

  def welcome

  end
private 
  def set_nav
   @post = Post.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 

  def coderay(text)
    text.gsub(/\<pre( lang="(.+?)")?\>\<code( lang="(.+?)")?\>(.+?)\<\/code\>\<\/pre\>/m) do
      lang = $4
      text = CGI.unescapeHTML($5).gsub /\<code( lang="(.+?)")?\>|\<\/code\>/, ""
      CodeRay.scan(text, lang).div(:css => :class)
    end
  end
 
  def full_title(page_title)
    base_title = "Hristo Georgiev"
    if page_title.empty?
      base_title
    else
      "#{page_title} • #{base_title}"
    end
  end

end 

app/helpers/backend/admin_index_helper.rb
module Backend::AdminIndexHelper
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper
end

app/helpers/backend/posts_helper.rb
module Backend::PostsHelper
end

app/helpers/backend/resource_helper.rb
module Backend::ResourceHelper
end

app/helpers/posts_helper.rb
module PostsHelper

   def tag_links(tags)
      tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) , :class=>'tag' }.join("  ")
   end


   def tag_cloud(tags, classes)
     max = tags.sort_by(&:count).last
     tags.each do |tag|
       index = tag.count.to_f / max.count * (classes.size-1)
       yield(tag, classes[index.round])
     end
   end


 end

app/views/backend/admin_index/index.html.erb

<div class="row" >

  <div class="small-12 large-12 columns" >
    <table>
      <thead>
        <tr>
          <th width="400">Title</th>
          <th width="200">Created at</th>
          <th width="350">Actions</th>
        </tr>
      </thead>

      <tbody>
      <% @posts.each do |p|%>
        <tr>
         <td><%=p.title %></td>
         <td><%=p.created_at %></td>
         <td>
           	<%= link_to "Show" , post_path(p.id)%>
         		|
           <%= link_to "Edit" , edit_backend_post_path(p.id)%>
         		|
            <%= link_to 'destroy', backend_post_path(p.id) , :method => :delete %>

          </td>
       </tr>
      <%end%>



     </tbody>

    </table>
  </div>

</div>

app/views/backend/posts/_preview.html.erb
  <%=   (coderay(RedCloth.new(@description).to_html)).html_safe %>

app/views/backend/posts/edit.html.erb
<div class="row">
   <div class="small-6 large-6 columns" id="edit ">

  <%= form_tag({:action => 'preview'}, :remote => true, :'data-update-target' => 'update-container') do %>
    <%= text_field_tag :title , @post.title , class: "pseudo-title" %>
  <%= text_area_tag(:description , @post.description ,:rows => 40, :cols => 120, :class => "pseudo-desc" )%>
  <%= submit_tag 'Preview post', :disable_with => 'Please wait...', :class => 'submit' %>
  <% end %>


    <%= form_for @post , url: backend_post_path(@post)   do |f| %>
        <%= f.hidden_field :title ,  :class=> "real-title" %>
        <%= f.hidden_field :description , :class => "real-desc", :rows => 40, :cols => 120 %>
         <%= f.text_field :all_tags, :placeholder => "Tags separated with comma" %>
        <%=  f.submit "Submit", :class => "btn btn-large btn-primary"   %>
     <% end %>


  </div>



  <div class="small-6 large-6 columns" id="update-container">


  </div>
</div>

<%= javascript_include_tag 'posts' %>

app/views/backend/posts/new.html.erb
	<div class="wrapper row">

	 <div class="small-6 large-6 columns">
		<%= form_tag({:action => 'preview'}, :remote => true, :'data-update-target' => 'update-container') do %>
		    <%= text_field_tag(:title, :title , class: "pseudo-title")%>
		  <%= text_area_tag(:description , :description ,  rows: 40 , cols: 120 , :class => "pseudo-desc" )%>
		  <%= submit_tag 'Preview post', :disable_with => 'Please wait...', :class => 'submit' %>
	  <% end %>
	</div>

  <%= form_for(:post , url: backend_posts_path) do |f| %>
      <%= f.hidden_field :title , :class=>"real-title"%>
      <%= f.hidden_field :description , :class => "real-desc", :rows => 40, :cols => 120 %>
			<%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
      <%=  f.submit "Submit", class: "btn btn-large btn-primary" %>
   <% end %>


	 <div class="small-6 large-6 columns" id="update-container">


	 </div>
</div>



<%= javascript_include_tag 'posts' %>

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag "favicon.ico" %>
    <%= render partial: "shared/meta" %>
      <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all"  %>
    <%= stylesheet_link_tag "coderay" %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "snap.svg-min.js" %>
    <%= javascript_include_tag "svg-anim.js" %>
    <%= javascript_include_tag "vendor/modernizr" %>

  </head>
  
  <body>

<div class="off-canvas-wrap"  data-offcanvas>
  <div class="inner-wrap" id="wrap">
    <nav class="tab-bar no-top-border">
        <section class="left-small">
            <a class="left-off-canvas-toggle menu-icon fixed" href="#"><span></span> </a>
        </section>
      </section>
    </nav>
    <%= render partial: "shared/header"%>
  <div class="toprow">
      <%= yield %>
    </div><a class="exit-off-canvas"></a>
</div>
 

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <%= favicon_link_tag "favicon.ico" %>
         <%= render partial: "shared/meta" %>
      <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all"  %>
    <%= stylesheet_link_tag "coderay" %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>

       <%= javascript_include_tag "main-nav-control.js" %>
    <%= javascript_include_tag "vendor/modernizr" %>

  </head>

  <body>

<div class="off-canvas-wrap"  data-offcanvas>
  <div class="inner-wrap" id="wrap">
    <nav class="tab-bar">
        <section class="left-small">
            <a class="left-off-canvas-toggle menu-icon fixed" href="#"><span></span> </a>
        </section>

        <section class="right-small">
          <a class="right-off-canvas-toggle archive" ><span>ARCHIVE</span></a>
        </section>
    </nav>

    <%= render partial: "shared/header"%>
    <%= render partial: "shared/archive" %>
 <div class=" large-12 columns">
    <section class="middle tab-bar-section row">
        <div class="title-header line-up"><%= link_to "Hristo Georgiev" , root_path %></div>
    </section>
</div>

      <%= yield %>
    </div>
  </div>

</div>

  </body>
</html>

app/views/layouts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <%= favicon_link_tag "favicon.ico" %>
          <%= render partial: "shared/meta" %>
      <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all"  %>
    <%= stylesheet_link_tag "coderay" %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "post-nav-control.js" %>
    <%= javascript_include_tag "vendor/modernizr" %>

  </head>

  <body>

<div class="off-canvas-wrap"  data-offcanvas>
  <div class="inner-wrap" id="wrap">
    <nav class="tab-bar">
        <section class="left-small">
            <a class="left-off-canvas-toggle menu-icon fixed" href="#"><span></span> </a>
        </section>
        <section class="right-small">
              <a class="right-off-canvas-toggle archive" ><span>ARCHIVE</span></a>
        </section>
    </nav>
    <%= render partial: "shared/header"%>
    <%= render partial: "shared/archive"%>
 <div class="toprow ">
    <section class="middle tab-bar-section row">
        <div class="title-header line-up"><%= link_to "Hristo Georgiev" , root_path %></div>
    </section>
  <div class="row push-down">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </div>
</div><a class="exit-off-canvas"></a>


  </body>
</html>

app/views/posts/_blog_nav.html.erb
<nav class="right-off-canvas-menu">

<% @posts_nav_months.sort.reverse.each do |year, post_month_group| %>
<ul class="off-canvas-list">
  <li><label><%=h year.strftime("%G") %></label></li>
  <% post_month_group.group_by { |t| t.created_at.beginning_of_month}.each do |month , posts_by_month| %>
  <li class="has-submenu"><a href="#"><%= h month.strftime("%B") %></a>
    <ul class="right-submenu">
      <li class="back"> <a href="#"> Back </a> </li>
      <li><label><%= h month.strftime("%B") %> </label></li>
      <% for post in posts_by_month %>
       <li name="<%= post.id %>" > <%= h link_to post.title %> </li>
      <%end%>
    </ul>
 </li>
  <%end%>


<%end%>
</nav>

app/views/posts/_disquis_comments.html.erb
<div class="wrapper">

 <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'hgeorgiev'; // required: replace example with your forum shortname
         var disqus_identifier = '<%= post.id %>';
 
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
</div>

app/views/posts/_post.html.erb
<div id="post-title-contain"> <h1 id="post-title" ><%= p.title %></h1></div>

    <div class="info-panel">
    Created at: <%= l(p.created_at , :format => :long)%>
    </div>
   <div class = "text">
      <%=   (coderay(RedCloth.new(p.description).to_html)).html_safe %>
    </div>


<div class="post-tags">

 <%=raw tag_links(p.all_tags) %>

 </div>

app/views/posts/_share_buttons.html.erb
<div class="social-share-buttons">
 <%= social_share_button_tag(p.title) %>
</div>

app/views/posts/index.html.erb
  <ul class="postslist toprow row push-down">
  <% if params[:tag] %>
    <h1 class="tagged-with"> Posts tagged with <span class="tagged-with-word"><%= params[:tag] %></span> </h1>
  <% end %>
  <% @posts.each do |post|%>

   <li>
    <h3 ><%= link_to "#{post.title}" , post %></h3>

      <div class="post-date-index"><%= post.created_at.to_formatted_s(:long) %></div>
   </li>

  <% end %>
</ul><a class="exit-off-canvas"></a>

app/views/posts/show.html.erb
<%  provide(:title , @post.title ) %>
<% set_meta_tags :og => { :title => @post.title } , :title => @post.title %>




<%= render partial: "share_buttons" , locals:{ p: @post} %>
<%= render partial: "post" , locals:{ p: @post}%>



<%= render partial: "disquis_comments" , :locals => { post: @post} %>

app/views/shared/_admin_header.html.erb
<nav class="top-bar" data-topbar role="navigation">

  <section class="top-bar-section">
   <!-- Right Nav Section -->
   <ul class="left">
     <li>  <%= link_to "Admin Panel" , backend_root_path %> </li>
     <li>  <%= link_to "Make a new blog post" , new_backend_post_path %></li>
   </ul>
 </section>

</nav>

app/views/shared/_archive.html.erb
<aside class="right-off-canvas-menu">
  <% @post_months.sort.reverse.each do |year, posts_by_month| %>
     <ul class="off-canvas-list">
       <li><label><%= year.strftime('%G')%> </label></li>
        <% posts_by_month.group_by { |t| t.created_at.beginning_of_month }.each do |month, posts| %>
       <li class="has-submenu"><a href="#"><%= h month.strftime('%B') %></a>
           <ul class="right-submenu">
               <li class="back"><a href="#">Back</a></li>
              <%for post in posts %>
               <li><%=link_to post.title , post_path(post.id) %></li>
              <% end %>
           </ul>

       </li>
        <%end%>
     </ul>
    <% end %>


      <div class="tags-cloud">
        <h4>Tag cloud</h4>
         <ul>
          <% tag_cloud Tag.counts, %w{tag-size-1 tag-size-2 tag-size-3 tag-size-4} do |tag, css_class| %>
            <li>
             <%= link_to tag.name, tag_path(tag.name), :class=> css_class  %>
            </li>
          <% end %>
        </ul>
     </div>
   </aside>

app/views/shared/_header.html.erb
<aside class="left-off-canvas-menu ">
    <div class="circular-sm"><%= link_to "" , root_path %></div>
    <p class="short-bio"> Developer, entrepreneur, fitness enthusiast. Studying Information Systems at <a href="http://www.aubg.edu" target="_blank">AUBG</a>. </p>

    <ul id="main-menu">
    <li><%= link_to "Blog" , posts_path(@post) %> </li>
    <li><a href="mailto:hgeorgievkzr@gmail.com">Contact</a></li>
    <li><%= link_to "About" , about_path%></li>

    </ul>
    <div id="profiles">
    <a href="http://stackoverflow.com/users/2808883/hristo-georgiev " target="_blank"><i class="hi-icon-header fi-social-stack-overflow size-40"></i></a>
    <a href="https://github.com/Kaizeras" target="_blank"><i class="hi-icon-header fi-social-github size-40"></i></a>
    <a href="https://www.linkedin.com/in/hggeorgiev" target="_blank"><i class="hi-icon-header fi-social-linkedin size-40"></i></a>


    </div>
   <% if  admin_signed_in? %>
    <div class= "admin-panel">
    <%= link_to "Log out" , destroy_admin_session_path , :method => :delete %>
    <%= link_to "Admin panel" , backend_root_path %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <% end %>
</aside>

app/views/shared/_meta.html.erb
<%= display_meta_tags :og => { :image => image_url("me.jpg") ,  :descritpion => "Hristo Georgiev's personal website" , :url => "www.hggeorgiev.com" , :site_name => "Hristo Georgiev's perosnal website" } , :keywords => "hristo georgiev kaizeras kzr instructor.bg ruby web html css js javascript developer entrepreneur biohacking tech rails ror on software development agile angular.js haml stackoverflow  html5 css3  jquery back end front end back-end front-end development" , :author => "Hristo Georgiev" %>